#!/bin/bash

echo "🧪 測試超時修復"
echo "================"
echo ""

echo "✅ 代碼已更新："
echo "  - 超時時間：60秒 → 120秒"
echo "  - 添加後端連接測試"
echo "  - 改進錯誤處理"
echo ""

echo "📦 代碼已推送到 GitHub"
echo "  - Render 將自動部署"
echo "  - 預計 2-3 分鐘完成"
echo ""

echo "⚠️  重要：在 Render Dashboard 設置環境變數"
echo "=================================="
echo ""
echo "1. 登入 Render Dashboard: https://dashboard.render.com"
echo ""
echo "2. 選擇 'health-nutrition-web' 服務"
echo ""
echo "3. 點擊 'Environment' 標籤"
echo ""
echo "4. 添加環境變數："
echo "   Key: NEXT_PUBLIC_API_URL"
echo "   Value: https://health-nutrition-api.onrender.com"
echo ""
echo "5. 點擊 'Save Changes'"
echo ""
echo "6. Render 會自動重新部署前端"
echo ""

echo "🧪 部署完成後測試步驟"
echo "===================="
echo ""
echo "1. 訪問前端: https://health-nutrition-web.onrender.com/photo"
echo ""
echo "2. 打開瀏覽器控制台 (F12)"
echo ""
echo "3. 上傳一張食物照片"
echo ""
echo "4. 查看控制台輸出，應該看到："
echo "   📤 發送請求到後端 API..."
echo "   🌐 API URL: https://health-nutrition-api.onrender.com"
echo "   🔍 測試後端連接..."
echo "   ✅ 後端連接正常，狀態: 200"
echo "   📤 發送照片識別請求..."
echo "   📥 收到後端回應，狀態: 200"
echo ""

echo "5. 如果看到 '❌ 後端連接失敗'："
echo "   - 檢查環境變數是否正確設置"
echo "   - 檢查後端服務是否正常運行"
echo "   - 查看 Render 日誌"
echo ""

echo "6. 如果還是超時："
echo "   - 檢查圖片大小（建議 < 1MB）"
echo "   - 查看 Render 後端日誌"
echo "   - 考慮使用本地分析（自動備選）"
echo ""

echo "📊 監控工具"
echo "=========="
echo ""
echo "Render Dashboard:"
echo "  - 前端: https://dashboard.render.com/web/srv-xxx"
echo "  - 後端: https://dashboard.render.com/web/srv-xxx"
echo ""
echo "查看日誌："
echo "  - 點擊服務 → Logs 標籤"
echo "  - 實時查看請求和錯誤"
echo ""

echo "✨ 預期改進"
echo "=========="
echo ""
echo "✅ 超時時間增加一倍（60秒 → 120秒）"
echo "✅ 更好的錯誤提示"
echo "✅ 自動連接測試"
echo "✅ 詳細的日誌輸出"
echo "✅ 自動回退到本地分析"
echo ""

echo "🎯 下一步"
echo "========"
echo ""
echo "1. 在 Render Dashboard 設置環境變數（最重要！）"
echo "2. 等待部署完成（2-3 分鐘）"
echo "3. 測試照片上傳功能"
echo "4. 查看控制台和 Render 日誌"
echo "5. 如果還有問題，告訴我具體的錯誤信息"
echo ""
