import { NutritionDatabaseDocument } from '../mongodb';

/**
 * 擴充的台灣/亞洲食物營養資料庫
 * 基於亞洲食物知識庫中的食材，補充完整營養資訊
 */
export const extendedTaiwanFoodNutritionData: Omit<NutritionDatabaseDocument, '_id' | 'created_at' | 'updated_at'>[] = [
  // ==================== 豆製品類 ====================
  {
    food_code: 'TW011',
    food_name: '豆腐干絲',
    food_name_en: 'Dried Tofu Strips',
    category: 'proteins',
    subcategory: '豆製品',
    energy_kcal: 140,
    protein_g: 16.5,
    fat_g: 6.2,
    carbohydrate_g: 4.8,
    fiber_g: 1.2,
    sugar_g: 0.5,
    sodium_mg: 450,
    calcium_mg: 350,
    iron_mg: 3.5,
    magnesium_mg: 45,
    phosphorus_mg: 180,
    potassium_mg: 220,
    zinc_mg: 1.2,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW012',
    food_name: '豆乾',
    food_name_en: 'Dried Tofu',
    category: 'proteins',
    subcategory: '豆製品',
    energy_kcal: 190,
    protein_g: 18.5,
    fat_g: 10.5,
    carbohydrate_g: 6.2,
    fiber_g: 1.5,
    sugar_g: 0.8,
    sodium_mg: 680,
    calcium_mg: 280,
    iron_mg: 4.2,
    magnesium_mg: 52,
    phosphorus_mg: 195,
    potassium_mg: 240,
    zinc_mg: 1.5,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },

  // ==================== 麵食類 ====================
  {
    food_code: 'TW013',
    food_name: '米粉',
    food_name_en: 'Rice Noodles',
    category: 'grains',
    subcategory: '米製品',
    energy_kcal: 109,
    protein_g: 1.9,
    fat_g: 0.2,
    carbohydrate_g: 24.9,
    fiber_g: 0.8,
    sugar_g: 0.3,
    sodium_mg: 3,
    calcium_mg: 8,
    iron_mg: 0.5,
    magnesium_mg: 12,
    phosphorus_mg: 35,
    potassium_mg: 28,
    zinc_mg: 0.4,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW014',
    food_name: '粉絲',
    food_name_en: 'Glass Noodles',
    category: 'grains',
    subcategory: '澱粉製品',
    energy_kcal: 351,
    protein_g: 0.2,
    fat_g: 0.1,
    carbohydrate_g: 87.8,
    fiber_g: 0.5,
    sugar_g: 0.1,
    sodium_mg: 10,
    calcium_mg: 18,
    iron_mg: 2.2,
    magnesium_mg: 8,
    phosphorus_mg: 22,
    potassium_mg: 15,
    zinc_mg: 0.3,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW015',
    food_name: '麵條',
    food_name_en: 'Wheat Noodles',
    category: 'grains',
    subcategory: '麵食',
    energy_kcal: 137,
    protein_g: 4.5,
    fat_g: 0.6,
    carbohydrate_g: 27.8,
    fiber_g: 1.2,
    sugar_g: 0.5,
    sodium_mg: 180,
    calcium_mg: 12,
    iron_mg: 1.2,
    magnesium_mg: 18,
    phosphorus_mg: 58,
    potassium_mg: 62,
    zinc_mg: 0.7,
    thiamine_mg: 0.08,
    riboflavin_mg: 0.04,
    niacin_mg: 1.5,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },

  // ==================== 蔬菜類 ====================
  {
    food_code: 'TW016',
    food_name: '玉米筍',
    food_name_en: 'Baby Corn',
    category: 'vegetables',
    subcategory: '根莖類',
    energy_kcal: 23,
    protein_g: 2.4,
    fat_g: 0.1,
    carbohydrate_g: 3.9,
    fiber_g: 2.0,
    sugar_g: 1.8,
    sodium_mg: 1,
    calcium_mg: 18,
    iron_mg: 0.5,
    magnesium_mg: 22,
    phosphorus_mg: 45,
    potassium_mg: 195,
    zinc_mg: 0.3,
    vitamin_a_ug: 8,
    vitamin_c_mg: 12.5,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW017',
    food_name: '糯米椒',
    food_name_en: 'Shishito Pepper',
    category: 'vegetables',
    subcategory: '果菜類',
    energy_kcal: 22,
    protein_g: 0.9,
    fat_g: 0.2,
    carbohydrate_g: 5.3,
    fiber_g: 1.5,
    sugar_g: 2.8,
    sodium_mg: 3,
    calcium_mg: 12,
    iron_mg: 0.4,
    magnesium_mg: 11,
    phosphorus_mg: 20,
    potassium_mg: 175,
    zinc_mg: 0.2,
    vitamin_a_ug: 48,
    vitamin_c_mg: 95.0,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW018',
    food_name: '青椒',
    food_name_en: 'Bell Pepper',
    category: 'vegetables',
    subcategory: '果菜類',
    energy_kcal: 20,
    protein_g: 0.9,
    fat_g: 0.2,
    carbohydrate_g: 4.6,
    fiber_g: 1.7,
    sugar_g: 2.4,
    sodium_mg: 2,
    calcium_mg: 10,
    iron_mg: 0.4,
    magnesium_mg: 10,
    phosphorus_mg: 20,
    potassium_mg: 175,
    zinc_mg: 0.1,
    vitamin_a_ug: 18,
    vitamin_c_mg: 80.4,
    vitamin_k_ug: 7.4,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },

  {
    food_code: 'TW019',
    food_name: '芹菜',
    food_name_en: 'Celery',
    category: 'vegetables',
    subcategory: '葉菜類',
    energy_kcal: 16,
    protein_g: 0.7,
    fat_g: 0.2,
    carbohydrate_g: 3.0,
    fiber_g: 1.6,
    sugar_g: 1.3,
    sodium_mg: 80,
    calcium_mg: 40,
    iron_mg: 0.2,
    magnesium_mg: 11,
    phosphorus_mg: 24,
    potassium_mg: 260,
    zinc_mg: 0.1,
    vitamin_a_ug: 22,
    vitamin_c_mg: 3.1,
    vitamin_k_ug: 29.3,
    folate_ug: 36,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  // ==================== 葉菜類 ====================
  {
    food_code: 'TW020',
    food_name: '空心菜',
    food_name_en: 'Water Spinach',
    category: 'vegetables',
    subcategory: '葉菜類',
    energy_kcal: 19,
    protein_g: 2.6,
    fat_g: 0.2,
    carbohydrate_g: 2.2,
    fiber_g: 2.2,
    sugar_g: 0.5,
    sodium_mg: 113,
    calcium_mg: 115,
    iron_mg: 2.5,
    magnesium_mg: 65,
    phosphorus_mg: 39,
    potassium_mg: 312,
    zinc_mg: 0.4,
    vitamin_a_ug: 225,
    vitamin_c_mg: 55.0,
    vitamin_k_ug: 108,
    folate_ug: 57,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW021',
    food_name: '青江菜',
    food_name_en: 'Bok Choy',
    category: 'vegetables',
    subcategory: '葉菜類',
    energy_kcal: 13,
    protein_g: 1.5,
    fat_g: 0.2,
    carbohydrate_g: 2.2,
    fiber_g: 1.0,
    sugar_g: 1.2,
    sodium_mg: 65,
    calcium_mg: 105,
    iron_mg: 0.8,
    magnesium_mg: 19,
    phosphorus_mg: 37,
    potassium_mg: 252,
    zinc_mg: 0.2,
    vitamin_a_ug: 223,
    vitamin_c_mg: 45.0,
    vitamin_k_ug: 45.5,
    folate_ug: 66,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },

  {
    food_code: 'TW022',
    food_name: '大白菜',
    food_name_en: 'Napa Cabbage',
    category: 'vegetables',
    subcategory: '葉菜類',
    energy_kcal: 13,
    protein_g: 1.5,
    fat_g: 0.2,
    carbohydrate_g: 2.2,
    fiber_g: 1.0,
    sugar_g: 1.2,
    sodium_mg: 57,
    calcium_mg: 77,
    iron_mg: 0.3,
    magnesium_mg: 13,
    phosphorus_mg: 30,
    potassium_mg: 238,
    zinc_mg: 0.2,
    vitamin_a_ug: 16,
    vitamin_c_mg: 27.0,
    vitamin_k_ug: 42.9,
    folate_ug: 79,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW023',
    food_name: '菠菜',
    food_name_en: 'Spinach',
    category: 'vegetables',
    subcategory: '葉菜類',
    energy_kcal: 23,
    protein_g: 2.9,
    fat_g: 0.4,
    carbohydrate_g: 3.6,
    fiber_g: 2.2,
    sugar_g: 0.4,
    sodium_mg: 79,
    calcium_mg: 99,
    iron_mg: 2.7,
    magnesium_mg: 79,
    phosphorus_mg: 49,
    potassium_mg: 558,
    zinc_mg: 0.5,
    vitamin_a_ug: 469,
    vitamin_c_mg: 28.1,
    vitamin_k_ug: 483,
    folate_ug: 194,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  // ==================== 菇類 ====================
  {
    food_code: 'TW024',
    food_name: '香菇',
    food_name_en: 'Shiitake Mushroom',
    category: 'vegetables',
    subcategory: '菇類',
    energy_kcal: 34,
    protein_g: 2.2,
    fat_g: 0.5,
    carbohydrate_g: 6.8,
    fiber_g: 2.5,
    sugar_g: 2.4,
    sodium_mg: 6,
    calcium_mg: 2,
    iron_mg: 0.4,
    magnesium_mg: 13,
    phosphorus_mg: 112,
    potassium_mg: 304,
    zinc_mg: 1.0,
    vitamin_d_ug: 0.4,
    niacin_mg: 3.9,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },

  {
    food_code: 'TW025',
    food_name: '金針菇',
    food_name_en: 'Enoki Mushroom',
    category: 'vegetables',
    subcategory: '菇類',
    energy_kcal: 37,
    protein_g: 2.7,
    fat_g: 0.3,
    carbohydrate_g: 7.6,
    fiber_g: 2.7,
    sugar_g: 3.2,
    sodium_mg: 5,
    calcium_mg: 1,
    iron_mg: 1.1,
    magnesium_mg: 13,
    phosphorus_mg: 105,
    potassium_mg: 359,
    zinc_mg: 0.5,
    niacin_mg: 6.1,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW026',
    food_name: '木耳',
    food_name_en: 'Wood Ear Mushroom',
    category: 'vegetables',
    subcategory: '菇類',
    energy_kcal: 25,
    protein_g: 1.5,
    fat_g: 0.2,
    carbohydrate_g: 6.5,
    fiber_g: 6.5,
    sugar_g: 0.6,
    sodium_mg: 8,
    calcium_mg: 30,
    iron_mg: 8.9,
    magnesium_mg: 51,
    phosphorus_mg: 82,
    potassium_mg: 166,
    zinc_mg: 0.7,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW027',
    food_name: '杏鮑菇',
    food_name_en: 'King Oyster Mushroom',
    category: 'vegetables',
    subcategory: '菇類',
    energy_kcal: 31,
    protein_g: 3.3,
    fat_g: 0.3,
    carbohydrate_g: 6.0,
    fiber_g: 2.3,
    sugar_g: 2.8,
    sodium_mg: 9,
    calcium_mg: 3,
    iron_mg: 0.5,
    magnesium_mg: 18,
    phosphorus_mg: 120,
    potassium_mg: 420,
    zinc_mg: 0.8,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW028',
    food_name: '鴻喜菇',
    food_name_en: 'Shimeji Mushroom',
    category: 'vegetables',
    subcategory: '菇類',
    energy_kcal: 26,
    protein_g: 2.7,
    fat_g: 0.3,
    carbohydrate_g: 5.1,
    fiber_g: 2.7,
    sugar_g: 2.3,
    sodium_mg: 6,
    calcium_mg: 2,
    iron_mg: 0.4,
    magnesium_mg: 14,
    phosphorus_mg: 108,
    potassium_mg: 350,
    zinc_mg: 0.6,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },

  // ==================== 台灣特色食材 ====================
  {
    food_code: 'TW029',
    food_name: '過貓',
    food_name_en: 'Guomao Fern',
    category: 'vegetables',
    subcategory: '蕨類蔬菜',
    energy_kcal: 27,
    protein_g: 3.2,
    fat_g: 0.3,
    carbohydrate_g: 4.5,
    fiber_g: 2.8,
    sugar_g: 0.6,
    sodium_mg: 5,
    calcium_mg: 85,
    iron_mg: 1.8,
    magnesium_mg: 42,
    phosphorus_mg: 55,
    potassium_mg: 285,
    zinc_mg: 0.5,
    vitamin_a_ug: 180,
    vitamin_c_mg: 35.0,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW030',
    food_name: '山蘇',
    food_name_en: 'Bird Nest Fern',
    category: 'vegetables',
    subcategory: '蕨類蔬菜',
    energy_kcal: 25,
    protein_g: 2.8,
    fat_g: 0.2,
    carbohydrate_g: 4.2,
    fiber_g: 3.0,
    sugar_g: 0.5,
    sodium_mg: 8,
    calcium_mg: 78,
    iron_mg: 1.6,
    magnesium_mg: 38,
    phosphorus_mg: 48,
    potassium_mg: 268,
    zinc_mg: 0.4,
    vitamin_a_ug: 165,
    vitamin_c_mg: 32.0,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },

  // ==================== 肉類 ====================
  {
    food_code: 'TW031',
    food_name: '豬肉',
    food_name_en: 'Pork',
    category: 'proteins',
    subcategory: '肉類',
    energy_kcal: 242,
    protein_g: 17.0,
    fat_g: 19.0,
    carbohydrate_g: 0,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 62,
    calcium_mg: 12,
    iron_mg: 1.0,
    magnesium_mg: 24,
    phosphorus_mg: 189,
    potassium_mg: 362,
    zinc_mg: 2.4,
    vitamin_b6_mg: 0.4,
    vitamin_b12_ug: 0.7,
    niacin_mg: 4.8,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW032',
    food_name: '雞肉',
    food_name_en: 'Chicken',
    category: 'proteins',
    subcategory: '禽肉類',
    energy_kcal: 165,
    protein_g: 31.0,
    fat_g: 3.6,
    carbohydrate_g: 0,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 82,
    calcium_mg: 15,
    iron_mg: 1.0,
    magnesium_mg: 29,
    phosphorus_mg: 228,
    potassium_mg: 256,
    zinc_mg: 1.0,
    vitamin_b6_mg: 0.5,
    niacin_mg: 8.5,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW033',
    food_name: '牛肉',
    food_name_en: 'Beef',
    category: 'proteins',
    subcategory: '肉類',
    energy_kcal: 250,
    protein_g: 26.0,
    fat_g: 15.0,
    carbohydrate_g: 0,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 72,
    calcium_mg: 18,
    iron_mg: 2.6,
    magnesium_mg: 21,
    phosphorus_mg: 173,
    potassium_mg: 318,
    zinc_mg: 4.8,
    vitamin_b12_ug: 2.6,
    niacin_mg: 5.8,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },

  // ==================== 海鮮類 ====================
  {
    food_code: 'TW034',
    food_name: '蝦',
    food_name_en: 'Shrimp',
    category: 'proteins',
    subcategory: '海鮮',
    energy_kcal: 99,
    protein_g: 20.9,
    fat_g: 1.2,
    carbohydrate_g: 0.9,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 148,
    calcium_mg: 70,
    iron_mg: 0.5,
    magnesium_mg: 34,
    phosphorus_mg: 237,
    potassium_mg: 259,
    zinc_mg: 1.6,
    vitamin_b12_ug: 1.1,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW035',
    food_name: '魚',
    food_name_en: 'Fish',
    category: 'proteins',
    subcategory: '海鮮',
    energy_kcal: 120,
    protein_g: 20.0,
    fat_g: 4.5,
    carbohydrate_g: 0,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 60,
    calcium_mg: 25,
    iron_mg: 0.8,
    magnesium_mg: 32,
    phosphorus_mg: 210,
    potassium_mg: 380,
    zinc_mg: 0.6,
    vitamin_d_ug: 5.0,
    vitamin_b12_ug: 3.5,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW036',
    food_name: '蝦米',
    food_name_en: 'Dried Shrimp',
    category: 'proteins',
    subcategory: '乾貨',
    energy_kcal: 312,
    protein_g: 63.7,
    fat_g: 4.5,
    carbohydrate_g: 2.8,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 4891,
    calcium_mg: 992,
    iron_mg: 3.2,
    magnesium_mg: 145,
    phosphorus_mg: 658,
    potassium_mg: 628,
    zinc_mg: 3.8,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },

  // ==================== 其他蔬菜 ====================
  {
    food_code: 'TW037',
    food_name: '豆芽',
    food_name_en: 'Bean Sprouts',
    category: 'vegetables',
    subcategory: '芽菜類',
    energy_kcal: 30,
    protein_g: 3.0,
    fat_g: 0.2,
    carbohydrate_g: 5.9,
    fiber_g: 1.5,
    sugar_g: 2.1,
    sodium_mg: 6,
    calcium_mg: 13,
    iron_mg: 0.9,
    magnesium_mg: 21,
    phosphorus_mg: 54,
    potassium_mg: 149,
    zinc_mg: 0.4,
    vitamin_c_mg: 13.2,
    folate_ug: 61,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW038',
    food_name: '韭菜',
    food_name_en: 'Chinese Chive',
    category: 'vegetables',
    subcategory: '葉菜類',
    energy_kcal: 27,
    protein_g: 2.4,
    fat_g: 0.5,
    carbohydrate_g: 4.6,
    fiber_g: 1.8,
    sugar_g: 1.9,
    sodium_mg: 8,
    calcium_mg: 42,
    iron_mg: 1.7,
    magnesium_mg: 25,
    phosphorus_mg: 38,
    potassium_mg: 247,
    zinc_mg: 0.4,
    vitamin_a_ug: 171,
    vitamin_c_mg: 24.0,
    vitamin_k_ug: 85.0,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW039',
    food_name: '洋蔥',
    food_name_en: 'Onion',
    category: 'vegetables',
    subcategory: '根莖類',
    energy_kcal: 40,
    protein_g: 1.1,
    fat_g: 0.1,
    carbohydrate_g: 9.3,
    fiber_g: 1.7,
    sugar_g: 4.2,
    sodium_mg: 4,
    calcium_mg: 23,
    iron_mg: 0.2,
    magnesium_mg: 10,
    phosphorus_mg: 29,
    potassium_mg: 146,
    zinc_mg: 0.2,
    vitamin_c_mg: 7.4,
    folate_ug: 19,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW040',
    food_name: '番茄',
    food_name_en: 'Tomato',
    category: 'vegetables',
    subcategory: '果菜類',
    energy_kcal: 18,
    protein_g: 0.9,
    fat_g: 0.2,
    carbohydrate_g: 3.9,
    fiber_g: 1.2,
    sugar_g: 2.6,
    sodium_mg: 5,
    calcium_mg: 10,
    iron_mg: 0.3,
    magnesium_mg: 11,
    phosphorus_mg: 24,
    potassium_mg: 237,
    zinc_mg: 0.2,
    vitamin_a_ug: 42,
    vitamin_c_mg: 13.7,
    vitamin_k_ug: 7.9,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },

  {
    food_code: 'TW041',
    food_name: '黃瓜',
    food_name_en: 'Cucumber',
    category: 'vegetables',
    subcategory: '果菜類',
    energy_kcal: 15,
    protein_g: 0.7,
    fat_g: 0.1,
    carbohydrate_g: 3.6,
    fiber_g: 0.5,
    sugar_g: 1.7,
    sodium_mg: 2,
    calcium_mg: 16,
    iron_mg: 0.3,
    magnesium_mg: 13,
    phosphorus_mg: 24,
    potassium_mg: 147,
    zinc_mg: 0.2,
    vitamin_c_mg: 2.8,
    vitamin_k_ug: 16.4,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW042',
    food_name: '筍子',
    food_name_en: 'Bamboo Shoot',
    category: 'vegetables',
    subcategory: '根莖類',
    energy_kcal: 27,
    protein_g: 2.6,
    fat_g: 0.3,
    carbohydrate_g: 5.2,
    fiber_g: 2.8,
    sugar_g: 3.0,
    sodium_mg: 6,
    calcium_mg: 13,
    iron_mg: 0.5,
    magnesium_mg: 3,
    phosphorus_mg: 59,
    potassium_mg: 533,
    zinc_mg: 1.1,
    vitamin_c_mg: 4.0,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW043',
    food_name: '絲瓜',
    food_name_en: 'Luffa',
    category: 'vegetables',
    subcategory: '果菜類',
    energy_kcal: 20,
    protein_g: 1.0,
    fat_g: 0.2,
    carbohydrate_g: 4.2,
    fiber_g: 1.0,
    sugar_g: 2.5,
    sodium_mg: 2,
    calcium_mg: 18,
    iron_mg: 0.4,
    magnesium_mg: 17,
    phosphorus_mg: 31,
    potassium_mg: 139,
    zinc_mg: 0.7,
    vitamin_c_mg: 8.0,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW044',
    food_name: '苦瓜',
    food_name_en: 'Bitter Melon',
    category: 'vegetables',
    subcategory: '果菜類',
    energy_kcal: 17,
    protein_g: 1.0,
    fat_g: 0.2,
    carbohydrate_g: 3.7,
    fiber_g: 2.6,
    sugar_g: 1.9,
    sodium_mg: 5,
    calcium_mg: 19,
    iron_mg: 0.4,
    magnesium_mg: 17,
    phosphorus_mg: 31,
    potassium_mg: 296,
    zinc_mg: 0.8,
    vitamin_c_mg: 84.0,
    folate_ug: 72,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW045',
    food_name: '茄子',
    food_name_en: 'Eggplant',
    category: 'vegetables',
    subcategory: '果菜類',
    energy_kcal: 25,
    protein_g: 1.0,
    fat_g: 0.2,
    carbohydrate_g: 5.9,
    fiber_g: 3.0,
    sugar_g: 3.5,
    sodium_mg: 2,
    calcium_mg: 9,
    iron_mg: 0.2,
    magnesium_mg: 14,
    phosphorus_mg: 24,
    potassium_mg: 229,
    zinc_mg: 0.2,
    vitamin_c_mg: 2.2,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },

  // ==================== 調味料 ====================
  {
    food_code: 'TW046',
    food_name: '蒜',
    food_name_en: 'Garlic',
    category: 'vegetables',
    subcategory: '調味料',
    energy_kcal: 149,
    protein_g: 6.4,
    fat_g: 0.5,
    carbohydrate_g: 33.1,
    fiber_g: 2.1,
    sugar_g: 1.0,
    sodium_mg: 17,
    calcium_mg: 181,
    iron_mg: 1.7,
    magnesium_mg: 25,
    phosphorus_mg: 153,
    potassium_mg: 401,
    zinc_mg: 1.2,
    vitamin_c_mg: 31.2,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW047',
    food_name: '薑',
    food_name_en: 'Ginger',
    category: 'vegetables',
    subcategory: '調味料',
    energy_kcal: 80,
    protein_g: 1.8,
    fat_g: 0.8,
    carbohydrate_g: 17.8,
    fiber_g: 2.0,
    sugar_g: 1.7,
    sodium_mg: 13,
    calcium_mg: 16,
    iron_mg: 0.6,
    magnesium_mg: 43,
    phosphorus_mg: 34,
    potassium_mg: 415,
    zinc_mg: 0.3,
    vitamin_c_mg: 5.0,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW048',
    food_name: '蔥',
    food_name_en: 'Scallion',
    category: 'vegetables',
    subcategory: '調味料',
    energy_kcal: 31,
    protein_g: 1.8,
    fat_g: 0.2,
    carbohydrate_g: 7.3,
    fiber_g: 2.6,
    sugar_g: 2.3,
    sodium_mg: 16,
    calcium_mg: 72,
    iron_mg: 1.5,
    magnesium_mg: 20,
    phosphorus_mg: 37,
    potassium_mg: 276,
    zinc_mg: 0.4,
    vitamin_a_ug: 50,
    vitamin_c_mg: 18.8,
    vitamin_k_ug: 207,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW049',
    food_name: '辣椒',
    food_name_en: 'Chili Pepper',
    category: 'vegetables',
    subcategory: '調味料',
    energy_kcal: 40,
    protein_g: 1.9,
    fat_g: 0.4,
    carbohydrate_g: 8.8,
    fiber_g: 1.5,
    sugar_g: 5.3,
    sodium_mg: 9,
    calcium_mg: 14,
    iron_mg: 1.0,
    magnesium_mg: 23,
    phosphorus_mg: 43,
    potassium_mg: 322,
    zinc_mg: 0.3,
    vitamin_a_ug: 48,
    vitamin_c_mg: 143.7,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },

  // ==================== 其他食材 ====================
  {
    food_code: 'TW050',
    food_name: '花生',
    food_name_en: 'Peanut',
    category: 'proteins',
    subcategory: '堅果類',
    energy_kcal: 567,
    protein_g: 25.8,
    fat_g: 49.2,
    carbohydrate_g: 16.1,
    fiber_g: 8.5,
    sugar_g: 4.7,
    sodium_mg: 18,
    calcium_mg: 92,
    iron_mg: 4.6,
    magnesium_mg: 168,
    phosphorus_mg: 376,
    potassium_mg: 705,
    zinc_mg: 3.3,
    vitamin_e_mg: 8.3,
    niacin_mg: 12.1,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW051',
    food_name: '白飯',
    food_name_en: 'White Rice',
    category: 'grains',
    subcategory: '米飯類',
    energy_kcal: 130,
    protein_g: 2.7,
    fat_g: 0.3,
    carbohydrate_g: 28.7,
    fiber_g: 0.4,
    sugar_g: 0.1,
    sodium_mg: 1,
    calcium_mg: 3,
    iron_mg: 0.2,
    magnesium_mg: 12,
    phosphorus_mg: 43,
    potassium_mg: 35,
    zinc_mg: 0.6,
    thiamine_mg: 0.02,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
  {
    food_code: 'TW052',
    food_name: '海帶',
    food_name_en: 'Kelp',
    category: 'vegetables',
    subcategory: '海藻類',
    energy_kcal: 43,
    protein_g: 1.7,
    fat_g: 0.6,
    carbohydrate_g: 9.6,
    fiber_g: 1.3,
    sugar_g: 0.6,
    sodium_mg: 233,
    calcium_mg: 168,
    iron_mg: 2.9,
    magnesium_mg: 121,
    phosphorus_mg: 42,
    potassium_mg: 89,
    zinc_mg: 1.2,
    data_source: '台灣食品營養成分資料庫',
    reference_year: 2023
  },
];
